= Welcome
:xrefstyle:full

This site is experimental. It is not an official documentation site (yet).

[cols="1a,1a"]
[grid=all]
[frame=all]


|====

|
=== eForms SDK
eForms is the new notification standard for public procurement procedures in the EU. The eForms SDK is a collection of resources, models and schemas providing the foundation for building eForms applications.

<<eforms:ROOT:index.adoc#, Read the docs>>


|
=== TED API
TED API is a collection of public interfaces allowing 3rd party applications to validate and submit eForms notices, publish tender documents, and search the TED archives.  

(Docs coming soon)
|
=== eProcurement Ontology
The eProcurement Ontology provides the formal, semantic foundation for the creation and reuse of linked open data in the domain of public procurement in the EU.  

<<EPO:ROOT:index.adoc#, Read the docs>>

|
=== ESPD exchange data model
The European Single Procurement Document is designed to accelerate processing of preliminary evidence in EU public procurement. The ESPD EDM enables applications to integrate with national ESPD service providers.
 
<<ESPD-EDM:ROOT:index.adoc#, Read the docs>>


|====