= Documentation for TED developers and eSenders

[.tile-container]
--

[.tile]
.eForms SDK
****
eForms is the new notification standard for public procurement procedures in the EU. The eForms SDK is a collection of resources, models and schemas providing the foundation for building eForms applications.

<<eforms:ROOT:index.adoc#, Read the docs>>
****

[.tile]
.TED API
****
TED API is a collection of public interfaces allowing 3rd party applications to validate and submit eForms notices, publish tender documents, and search the TED archives.

<<api:ROOT:index.adoc#, Read the docs>>
****

[.tile]
.eProcurement Ontology
****
The eProcurement Ontology provides the formal, semantic foundation for the creation and reuse of linked open data in the domain of public procurement in the EU.

<<EPO:ROOT:index.adoc#, Read the docs>>
****

[.tile]
.TED Open Data
****
Access TED Open Data via direct queries to our SPARQL endpoint or download TED Notice XML Data. Learn how to reuse our RML mappings to transform XML data into RDF.

[.button]
<<ODS:ROOT:index.adoc#, Read the docs>>
****

[.tile]
.ESPD-EDM
****
The European Single Procurement Document enables accelerated processing of preliminary evidence in EU public procurement. The ESPD-EDM enables applications to integrate with national ESPD service providers.

[.button]
<<ESPD-EDM:ROOT:index.adoc#, Read the docs>>
****


[.tile]
.model2owl
****
"model2owl" is a tool for transforming human-readable semantic models into machine-readable OWL files and SHACL shapes

<<M2O:ROOT:index.adoc#, Read the docs>>

****
--
